# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

profiles = Profile.create([
	{ name: 'Database Administrator', description: "This fast-growing profession involves setting up databases to fit a company's need, then maintaining those database's operations. This will typically involve proactive periodic monitoring and troubleshooting. The DBA handles lots of database security, ensuring that only authorized users have access to the database and fortifying it against any external, unauthorized access. If this is you, then you will be handling the database tuning which include tweaking any of several parameters to optimize performance, such as server memory allocation, file fragmentation and disk usage.", salary: '$87,500-$126,000'
	},
	{ name: 'Project Manager', description: "The project manager acts as a liaison between stakeholders and technical team. This individual will also define and manage all aspects of the project including scope, scheduling, staffing, issues and budget. If this is the job for you, you will be leading your team through product creation. You will facilitate all project meetings, including business process designing and project status meetings.", salary: '$88,500-$131,000'
	},
	{ name: 'Quality Assurance', description: "The QA Analyst role will be responsible for defining / creating test criteria for software, website, or products.  You will be creating in-depth test cases / test suites to ensure maximum coverage of features & functionalities as well as keeping the end user experience and overall schedule(s) in mind. You will be participating in planning and directing testing milestones/schedules and assignments, and monitoring project status in comparison to cost/time projections. Documenting is a huge part of your daily tasks, you will need to log, track, and verify resolution of software and specification defects. As a QA, you will get to learn a lot just purely on the tests you conduct daily from developers.", salary: '$60,250-$93,500'
	},
	{ name: 'Software Engineer', description: 'These professionals are the brains behind your Candy Crush obsession and Android phone dependency. They might be applications developers, who design computer software, databases and games, or they could be systems-focused developers, who are responsible for building operating systems. You would work closely with senior programmers and business analysts, and create technical plans to meet the needs of the client. Let’s not forget about assisting with the functional documentation of customer business requirements. If this is you, you will always have a great role creating some of the hottest products in the tech industry!  
', salary: '$89,750-$137,250' 
	},
	{ name: 'Web Developer', description: "Web developers are responsible for the sleek fonts and clean layout you love on your favorite websites. As a web developer you could work for a variety of businesses and public sector organizations. If you are a web developer, your job has many components, but don’t worry, once you create that polished web site, you will have 1,000 bragging points! You will be building the framework – or 'architecture' – of the site and add the command buttons, payment systems and video, sound or animation. You will be making sure that the new site can be smoothly integrated into the client's existing network, for instance linking with a customer database. You will be working on the site's appearance, often with a web designer. Last but not least, once you have built the site, you may continue to make minor changes to make sure the site is working properly and meets all the client's.", salary: '$70,000-$113,000' 
	},
	{ name: 'UX/UI Designer', description: "These are your “Steve Jobs” of the tech world. As a UX/UI (User Experience/User Interface)  designer, you are responsible for designing satisfying or compelling experience for users of a product or website, often drawing on results from user research and workflow analysis. You may be responsible for producing personas, usage scenarios, sitemaps, taxonomies and wireframes, and for conducting usability testing on prototypes or finished products to assess the quality of a user experience. You should also have an expert understanding of graphic design and web technologies. Your daily task include: working closely with the developers, graphic designers, and project managers to build beautiful, user centric, easy to use applications. Always keep updated with design principles and current industry trends!", salary: '$79,000-$118,000'
	},
]);